name: Accessibility Validation

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 11.x
      uses: actions/setup-node@v1
      with: 
        node-version: 11.x
      
    - name: Scan for A11y issues
      uses: microsoft/accessibility-insights-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        site-dir: ${{ github.workspace }}/
        output-dir: ${{ github.workspace }}/_accessibility-reports 
        
    - name: Upload report artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: accessibility-reports
        path: ${{ github.workspace }}/_accessibility-reports  
